### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by Hellioob** [notabenoid/notabenoid#8]
Hi! How to install this notabenoid with docker ? 
Put this command "docker run --rm -p 127.0.0.1:8080:80 opennota/notabenoid"  and download all files, but then go to http://localhost:8080 not charging anything

Error: positional arguments are not supported
For help, use /usr/bin/supervisord -h

**Comment by opennota** [comment]
Did you terminate the program with Ctrl+C? If not, can you show the output of the command?

**Comment by Hellioob** [comment]
pushed Ctrl + C what next ?

**Comment by opennota** [comment]
You shouldn't. Neither should it exit by itself.

Try now. I updated the image on the Docker Hub.

```
docker pull opennota/notabenoid
docker run --rm -p 127.0.0.1:8080:80 opennota/notabenoid
```

Then wait for
```
2015-11-21 14:04:28,512 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-11-21 14:04:28,512 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-11-21 14:04:28,512 INFO success: postgresql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-11-21 14:04:28,512 INFO success: memcached entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-11-21 14:04:28,512 INFO success: php5-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
and go to [http://localhost:8080](http://localhost:8080). Then you hopefully can log in as admin/admin.

**Comment by Hellioob** [comment]
very thanks!

**Comment by Hellioob** [comment]
Is it possible to translate the site into another language?

**Comment by opennota** [comment]
The English localization is planned, but isn't going to be ready soon. Alternatively you can fork the repository and translate all the text chunks in the files yourself.

**Comment by Hellioob** [comment]
I'm sorry but I'm confused! Where are these files?
Folder notabenoid\files is empty

**Comment by opennota** [comment]
[protected/controllers](https://github.com/notabenoid/notabenoid/tree/master/protected/controllers), [protected/models](https://github.com/notabenoid/notabenoid/tree/master/protected/models), [protected/views](https://github.com/notabenoid/notabenoid/tree/master/protected/views), probably some files under [www](https://github.com/notabenoid/notabenoid/tree/master/www).

**Comment by Hellioob** [comment]
after changing how to put the changes ?

**Comment by opennota** [comment]
Use https://github.com/notabenoid/notabenoid-dockerfile to build your own image.

**Comment by Hellioob** [comment]
Hi! after command "docker run --rm --entrypoint grep notabenoid www-data /etc/group" I get it
https://imgur.com/FSHMoI3

**Comment by opennota** [comment]
You didn't build the image.

> From this point on I'm assuming that you already have built an image named notabenoid.

The documentation is also slightly out of date. The steps "Get the ID of the group www-data inside the container" and "Create necessary directories and set permissions so that the web server running in the container could write to them" aren't needed anymore.

**Comment by Hellioob** [comment]
command "docker build -t notabenoid ." I have to fulfill mandatory?

sorry bad english!

**Comment by opennota** [comment]
Yes, you have.

**Comment by opennota** [comment]
Or no. You can use the image you already have. Its name is `opennota/notabenoid`, not `notabenoid`.

**Comment by Hellioob** [comment]
hi! again failed.
http://i.imgur.com/xhU3eTm.png

**Comment by opennota** [comment]
There is a dot in the end of the command: `docker build -t notabenoid .`

**Comment by opennota** [comment]
And you already have then `opennota/notabenoid` repository. Choose a different name.

**Comment by Hellioob** [comment]
http://i.imgur.com/FUuLLdB.png

**Comment by opennota** [comment]
Is your current directory a root of the forked `notabenoid-dockerfile` repository (it should be) or are you trying to execute this command in the home directory?

**Comment by Hellioob** [comment]
I managed to create image, but last command don't work!

`< docker run -v `pwd`:/srv/example.com -p 127.0.0.1:8080:80 --name notabenoid notabenoid >`
https://imgur.com/pwNsteN

**Comment by opennota** [comment]
Instead of `pwd` in backticks type the full path (staring with `/`) to the directory with the notabenoid code. Instead of `/srv/example.com` type `/notabenoid/site`:

```
docker run -v /full/path/to/the/notabenoid:/notabenoid/site -p 127.0.0.1:8080:80 --name notabenoid notabenoid
```

**Comment by Hellioob** [comment]
Hi! againt fault. trying to put space between 
'< `pwd` here! :/  >' I get an error about port
http://i.imgur.com/oTPrz1L.png

**Comment by opennota** [comment]
Which word you didn't understand?

**Comment by Hellioob** [comment]
sorry, i am amateur! 
1- Download notabenoid-dockerfile-master.zip and exact to C:\Users\my user.
2- Run Docker Quickstart Terminal and write '<cd notabenoid-dockerfile-master>'
3- write '<docker build -t notabenoid .>' starts to download, no problem http://i.imgur.com/8d3aKwK.png
4-write '<docker run -p 127.0.0.1:8080:80 --name notabenoid notabenoid>' start to download and run, no problem.
5-clone  '<git clone https://github.com/notabenoid/notabenoid.git>' start to full clone to my folder notabenoid-dockerfile-master and create automatically folder "notabenoid"
6-write '<cd notabenoid>' 
7-write '<docker run -v `pwd`:/notabenoid/site -p 127.0.0.1:8080:80 --name notabenoid notabenoid>' or '<docker run -v /full/path/to/the/notabenoid:/notabenoid/site -p 127.0.0.1:8080:80 --name notabenoid notabenoid>' out error http://i.imgur.com/oTPrz1L.png

Sorry, I do not know what it means error.

**Comment by opennota** [comment]
> Instead of pwd in backticks type the full path (starting with /) to the directory with the notabenoid code. Instead of /srv/example.com type /notabenoid/site

**Comment by opennota** [comment]
I'm closing the issue because the original problem is solved and I can't possibly help with any problems with using Docker specific to mingw/windows.

**Comment by Hellioob** [comment]
thanks for help!
